# Generated by Django 4.1.3 on 2022-12-05 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(to='web.product'),
        ),
        migrations.CreateModel(
            name='ShoppingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
                ('shoppingcart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.shoppingcart')),
            ],
        ),
    ]
