# Generated by Django 4.1.3 on 2022-12-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_shoppingcart_product_shoppingproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shoppingproduct',
            old_name='shoppingcart_id',
            new_name='shoppingcart',
        ),
    ]
