# Generated by Django 4.1.3 on 2022-12-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_product_id_shoppingproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(through='web.ShoppingProduct', to='web.product'),
        ),
    ]
