# Generated by Django 4.1.3 on 2022-12-05 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_shoppingcart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
